### ISSUE TITLE
Crash when `Preferences` is clicked.

### ISSUE THREAD

**Issue by parzival2** [cosmonium/cosmonium#20]
Very nice to see this project. Its very beautiful. 
I have noticed that the software crashes when the `Preferences` button is clicked. Unfortunately, I am still going through the code so I wont be of much help this soon. Just wanted to let you know. I will try to create a pull-request if I get around understanding the code and solved the problem successfully. 
Please let me know how I can be of further assistance. If I can provide you some logs I would gladly do so. 
Thanks.

**Comment by el-dee** [comment]
I'm sorry, the bug is already solved in the develop branch, but I still need to upload a development build with the fix...

The bug is that the model used to display the spin buttons of the preference (and editor) windows is missing and so the app crash as it can not load it

And thanks a lot for your offer to investigate this bug ! The code is still a bit messy but I hope to rework the inner architecture in the following months and stabilise the core :)

**Comment by parzival2** [comment]
Ah good to hear that it is already fixed. Good to hear, the project looks very good and it has a lot of potential.

**Comment by el-dee** [comment]
This is fixed in V0.2.1 (https://github.com/cosmonium/cosmonium/releases/tag/v0.2.1)
