### ISSUE TITLE
Zoom can move user in wrong direction or reset altitude to 0

### ISSUE THREAD

**Issue by C1ffisme** [cosmonium/cosmonium#37]
I decided to try out Cosmonium on my main PC instead of my [PopOS laptop](https://github.com/cosmonium/cosmonium/issues/36), where textures rendered correctly, but I've noticed zooming in and out with the scrollwheel is... broken:

- When zooming out from objects, the direction you zoom out seems to become perpendicular to the direction of the object
- Zooming in and out around this spot a lot seems to get you stuck in the corner
- Occasionally, zooming in or out or panning from a certain distance will just reset your altitude or distance to 0, sending you straight to the center of the object. This is especially noticeable with Barycenters where it happens almost every time you zoom out.

![cosmonium_zoom-ezgif com-resize](https://github.com/cosmonium/cosmonium/assets/9893266/80812d14-9ce2-4a83-a37e-53bb78162f79)

Version is `0.3.0.dev837_manylinux2014_x86_64.tar.gz`, OS is Linux Mint 21.3 Cinnamon.

**Comment by el-dee** [comment]
This is a regression introduced when I refactored the navigation controller...

In Cosmonium, the position of an object is always relative to a local reference point, and the observer's position is also always relative to the closest reference point.
The issue happens when the camera switch from the target reference point to a closer one: the distance calculation used for the zoom is still using the previous reference point and so the distance, and direction, start to diverge (or get stuck as in the wrong reference system, the observer is at the surface of the target object)

**Comment by el-dee** [comment]
This is fixed in d5ad9e80a1f3869244f30c5320bf3a86a8da55cd and 55744775fdbf1c64fd25406c199d97ac1153aca7
A new dev build will be made shortly.
