### ISSUE TITLE
Add more moons

### ISSUE THREAD

**Issue by SevenSpheres** [cosmonium/cosmonium#9]
Many moons are missing. Also:
"Kerebos" should be Kerberos
Haumea's rings are missing
The name Hi'iaka is rendered as mojibake

**Comment by el-dee** [comment]
> Many moons are missing. Also:
"Kerebos" should be Kerberos

All the missing irregular moons have been added in https://github.com/cosmonium/cosmonium/commit/3eabb9a9346706e58fa58db17ece84fe9848cf7a (And Kerberos name is fixed)

>  The name Hi'iaka is rendered as mojibake

Fixed in https://github.com/cosmonium/cosmonium/commit/810ab7068a1d3152ba30de5cea4bca46da3af2e0

Missing rings (Haumea, but also Uranus, Jupiter and Neptune) will be added later

**Comment by el-dee** [comment]
Procedural rings for Haumea and actual rings for Uranus added in https://github.com/cosmonium/cosmonium/commit/62d7155c27e0845ca91ddb438428f187e7f63e30

![Haumea rings](https://user-images.githubusercontent.com/44778133/67897995-c198eb00-fb5f-11e9-8d0f-e3cf9c2f7a02.png)

![Unranus rings](https://user-images.githubusercontent.com/44778133/67898016-cbbae980-fb5f-11e9-9d9d-5452e45c379c.png)
